name: Gradle CI

on:
  push:
    branches:
      - 2025.2

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MCREATOR_VERSION: 2025.2.28610

    steps:
      - name: Checkout Generator
        uses: actions/checkout@v4

      - name: Checkout MCreator repository
        uses: actions/checkout@v4
        with:
          repository: MCreator/MCreator
          ref: ${{ env.MCREATOR_VERSION }}
          path: mcreator

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run MCreator Test With Plugin
        env:
          MCREATOR_PATH: ${{ github.workspace }}/mcreator
        run: ./gradlew test